# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/fleet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/fleet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/fleet.proto\x12\x05\x66leet\"$\n\x0eVehicleRequest\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\"b\n\x0fVehicleResponse\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\x12\x15\n\raverage_speed\x18\x02 \x01(\x01\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x14\n\x0clast_updated\x18\x04 \x01(\t2Q\n\x0c\x46leetService\x12\x41\n\x10GetVehicleStatus\x12\x15.fleet.VehicleRequest\x1a\x16.fleet.VehicleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.fleet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICLEREQUEST']._serialized_start=28
  _globals['_VEHICLEREQUEST']._serialized_end=64
  _globals['_VEHICLERESPONSE']._serialized_start=66
  _globals['_VEHICLERESPONSE']._serialized_end=164
  _globals['_FLEETSERVICE']._serialized_start=166
  _globals['_FLEETSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
